"""empty message

Revision ID: 2bc5a421cb06
Revises: 70e688ba1f42
Create Date: 2020-12-02 00:29:49.878218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc5a421cb06'
down_revision = '70e688ba1f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute('UPDATE questions SET category = 8 WHERE category IS NULL;')
    op.execute('ALTER TABLE questions ALTER COLUMN category TYPE integer USING(category::integer);')
    op.alter_column('questions', 'category',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.create_foreign_key(None, 'questions', 'categories', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.alter_column('questions', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
